### ISSUE TITLE
支持title自定义

### ISSUE THREAD

**Issue by nevermore-kl** [wefront/we-easydoc#1]
```js
// src/views/panel
<a class="title" target="_blank" href="https://juejin.cn/team/6932676282429898766/posts"> Easy-Doc </a>
```
title,href支持自定义,或者不需要跳转

**Comment by liyuntong2016** [comment]
自动回复邮件：
您好，我是李运通，邮件已收到
祝您开心每一天。

**Comment by liyuntong2016** [comment]
我们在2.2.2版本中修改了这个问题。
可以在初始化的时候传参EasyDocDocumentUrl：false 让点击的时候不再跳转；
或者 EasyDocDocumentUrl：‘自定义URL’ 让点击的时候跳到自定义的位置；
默认依然是跳到掘金EasyDoc介绍文档地址
`
EasyDoc.init({
        easyDocPath: "../public/easy-doc/EasyDoc.json",
        easyManualsPath: "../public/easy-doc/Manuals.json",
        easyProjectsPath: "../public/easy-doc/Projects.json",
        EasyDocDocumentUrl: false
      });
`
