### ISSUE TITLE
每次打开页面，右上角都会创建新的浮动菜单

### ISSUE THREAD

**Issue by tuhe32** [wefront/we-easydoc#3]
![image](https://user-images.githubusercontent.com/18496264/148486152-75cab9d0-75f4-4b01-9ea3-7527b348c95a.png)

 每次打开页面，右上角都会创建新的浮动菜单，旧的被压在下面没有被清除，即使重复打开同一个页面，仍然会创建新的，旧的不会被清理，首先不美观，然后可能会影响页面性能

**Comment by liyuntong2016** [comment]
自动回复邮件：
您好，我是李运通，邮件已收到
祝您开心每一天。

**Comment by liyuntong2016** [comment]
这是一个不再预期内的问题，大概是因为你刷新页面导致执行了多次EasyDoc.init()产生的。我们已在2.2.3版本调整为每次调用时先清除掉旧的实例再创建。

升级2.2.3版本即可解决
